name: Coverage Report

on:
  workflow_run:
    workflows: ['CI_Main']
    branches: [main]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'push' && github.event.workflow_run.head_branch == 'main' }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm ci
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: b7a890bbaf551006ae0db629030ec347c3b05d026220ba994ec0a46d40377d08
        with:
          coverageCommand: npm run coverage