name: Publich github pages

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'demoSrc/**'
      - 'package.json'
      - 'README.md'
      - 'tsconfig**.json'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm ci
      - name: Genarate API Pages
        run: npx typedoc --out ./docs/api src/index.ts
      - name: Generate Demo Pages
        run: npx gulp bundleDemo